version: '1'

services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=ensolversdb
    ports:
      - 5432:5432

  backend:
    build: ./backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PORT=3000
      - DB_URI=postgres://postgres:postgrespass@postgres:5432/ensolversdb

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
